name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }} os ${{ matrix.os }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn build
    - run: yarn test

    - name: Coverage core-validator
      uses: coverallsapp/github-action@v1
      with: 
        - base-path: "packages/core-validator"
        - github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Coverage validator
      uses: coverallsapp/github-action@v1
      with: 
        - base-path: "packages/validator"
        - github-token: ${{ secrets.GITHUB_TOKEN }}
